on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.5
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export

      - name: West Build (Dactyl Manu Left)
        run: west build -s zmk/app -b particle_xenon -- -DSHIELD=dactyl_manuform_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Dactyl Manu DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/particle_xenon.dts.pre.tmp
      - name: Dactyl Manu Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 dactyl_manuform_left_particle_xenon.uf2
      - name: Archive (Dactyl Manu Left)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: dactyl_manuform_left_particle_xenon.uf2

      - name: West Build (Dactyl Manu Right)
        run: west build --pristine -s zmk/app -b particle_xenon -- -DSHIELD=dactyl_manuform_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Dactyl Manu Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 dactyl_manuform_right_particle_xenon.uf2
      - name: Archive (Dactyl Manu Right)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: dactyl_manuform_right_particle_xenon.uf2


      - name: West Build (Particle Reset)
        run: west build -s zmk/app -b particle_xenon -- -DSHIELD=settings_reset_particle -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Dactyl Manu DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/particle_xenon.dts.pre.tmp
      - name: Particle Reset Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 settings_reset_particle_particle_xenon.uf2
      - name: Archive (Dactyl Manu Left)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: settings_reset_particle_particle_xenon.uf2
